apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-java-springboot-basic
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/msawood-tenant/devfile-sample-java-springboot-basic/devfile-sample-java-springboot-basic@sha256:15133f5322c9043d92ef92c56c402973a923e3607d8cafc981d72343fcdfeead
        name: my-java-springboot
        resources: {}
status: {}
